- name: Create SSL certificate
  hosts: all
  become: yes
  vars:
    cert_dir: /etc/ssl/certs
    cert_name: ssl_webserver.crt
    key_name: ssl_webserver.key
    csr_name: ssl_webserver.csr
    days_valid: 1
    common_name: webserver.com
  tasks:

    - name: Generate SSL key
      openssl_privatekey:
        path: "{{ cert_dir }}/{{ key_name }}"

    - name: Generate CSR
      openssl_csr:
        path: "{{ cert_dir }}/{{ csr_name }}"
        privatekey_path: "{{ cert_dir }}/{{ key_name }}"
        common_name: "{{ common_name }}"

    - name: Generate SSL certificate
      openssl_certificate:
        path: "{{ cert_dir }}/{{ cert_name }}"
        privatekey_path: "{{ cert_dir }}/{{ key_name }}"
        csr_path: "{{ cert_dir }}/{{ csr_name }}"
        provider: selfsigned
        selfsigned_not_after: +1d2h

    - name: Check if SSL certificate needs renewal
      stat:
        path: "{{ cert_dir }}/{{ cert_name }}"
      register: cert_stat
    - name: Renew SSL certificate if it is expired
      when: cert_stat.stat.exists and cert_stat.stat.ctime < ((days_valid * 86400) * 0.5)
      openssl_certificate:
        path: "{{ cert_dir }}/{{ cert_name }}"
        privatekey_path: "{{ cert_dir }}/{{ key_name }}"
        csr_path: "{{ cert_dir }}/{{ csr_name }}"
        provider: selfsigned
        days_valid: "{{ days_valid }}"

    - name: Copy certificate to web server
      copy:
        src: "{{ cert_dir }}/{{ cert_name }}"
        dest: /home/jenkins/{{ cert_name }}
        remote_src: yes
